name: Check code quality

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint the codebase
        uses: psf/black@stable
        with:
          options: "--check --diff"
      - name: Type checking
        run: |
          pip install mypy
          mypy --ignore-missing-imports .
