name: Build and test

on: pull_request

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        sudo apt-get update
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt
    - name: Build and start database
      run: |
        sudo apt-get install postgresql
        sudo apt-get install postgresql-server-dev-10
        sudo service postgresql start
        psql --username=postgres --no-password --command="CREATE DATABASE osspackrat_test;"
        psql --username=postgres --no-password --dbname=osspackrat_test --file=create_tables.sql
        psql --username=postgres --no-password --dbname=osspackrat_test --file=test_seed_data.sql
    - name: Test with pytest
      run: |
        pytest
